const fs=require('fs'),path=require('path'),crypto=require('crypto');const {chromium}=require('playwright');
const out='/root/.hermes/profiles/frontend/workspace/nodeck-clone/RECON/journey';fs.mkdirSync(out,{recursive:true});
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{const browser=await chromium.launch({headless:true});
async function make(url){const ctx=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1,reducedMotion:'reduce'});const p=await ctx.newPage();const errors=[],consoleIssues=[],httpErrors=[],failed=[];p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(['error','warning'].includes(m.type())&&!m.text().includes('GL Driver Message'))consoleIssues.push({type:m.type(),text:m.text()})});p.on('response',r=>{if(r.status()>=400)httpErrors.push({url:r.url(),status:r.status()})});p.on('requestfailed',r=>failed.push({url:r.url(),failure:r.failure()}));await p.goto(url,{waitUntil:'networkidle',timeout:90000});await p.waitForTimeout(1800);return {ctx,p,errors,consoleIssues,httpErrors,failed}}
const orig=await make('https://www.nodeck.online/'), clone=await make('http://127.0.0.1:44118/');
async function state(p){return p.evaluate(()=>{const vis=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&+s.opacity>0&&r.width>0&&r.height>0};const clean=s=>(s||'').trim().replace(/\s+/g,' ');return {url:location.pathname,bg:getComputedStyle(document.body).backgroundColor,active:[...document.querySelectorAll('.slide.is-active')].map(e=>e.className),counter:[...document.querySelectorAll('*')].filter(e=>vis(e)&&/^SLIDE \d+\/10$/.test(clean(e.textContent))).map(e=>clean(e.textContent))[0]||'',text:clean(document.body.innerText).slice(0,1800),visible:[...document.querySelectorAll('button,a')].filter(vis).map(e=>({tag:e.tagName,cls:e.className,text:clean(e.textContent).slice(0,100),aria:e.getAttribute('aria-label'),href:e.getAttribute('href')})).slice(0,50),overlay:document.querySelector('.nav-overlay')?.className||'',notes:[...document.querySelectorAll('[class*=notes]')].filter(vis).map(e=>({cls:e.className,text:clean(e.textContent).slice(0,300)})).slice(0,10),sound:document.querySelector('.sound-toggle')?.className||'',resources:performance.getEntriesByType('resource').map(x=>x.name.replace(location.origin,'')).sort()}})}
function canonical(s){const x=structuredClone(s);delete x.text;return x}
const results=[];async function checkpoint(label,shoot=false){const [a,b]=await Promise.all([state(orig.p),state(clone.p)]);let shots=null;if(shoot){const [ab,bb]=await Promise.all([orig.p.screenshot(),clone.p.screenshot()]);shots={orig:sha(ab),clone:sha(bb),equal:sha(ab)===sha(bb)};fs.writeFileSync(path.join(out,label+'-original.png'),ab);fs.writeFileSync(path.join(out,label+'-clone.png'),bb)}const sa=JSON.stringify(a),sb=JSON.stringify(b);results.push({label,equal:sa===sb,canonicalEqual:JSON.stringify(canonical(a))===JSON.stringify(canonical(b)),shots,a,b});return {a,b}}
async function click(sel){await Promise.all([orig.p.locator(sel).evaluate(e=>e.click()),clone.p.locator(sel).evaluate(e=>e.click())])}
await checkpoint('start',true);
let lastCounter='';let sameAtLast=0;for(let i=1;i<=32;i++){await click('.nav__arrow--next');await Promise.all([orig.p.waitForTimeout(1900),clone.p.waitForTimeout(1900)]);const s=await checkpoint('forward-'+String(i).padStart(2,'0'),i%4===0);const c=s.a.counter;if(c==='SLIDE 10/10'&&c===lastCounter)sameAtLast++;else sameAtLast=0;lastCounter=c;if(sameAtLast>=2)break}
// Open menu, close, notes, sound.
await click('.nav__menu');await Promise.all([orig.p.waitForTimeout(500),clone.p.waitForTimeout(500)]);await checkpoint('menu-open',true);
await click('.nav-overlay__close');await Promise.all([orig.p.waitForTimeout(300),clone.p.waitForTimeout(300)]);await checkpoint('menu-closed');
await click('.notes-button');await Promise.all([orig.p.waitForTimeout(500),clone.p.waitForTimeout(500)]);await checkpoint('notes-open',true);
await Promise.all([orig.p.keyboard.press('Escape'),clone.p.keyboard.press('Escape')]);await Promise.all([orig.p.waitForTimeout(300),clone.p.waitForTimeout(300)]);await checkpoint('notes-closed');
await click('.sound-toggle');await Promise.all([orig.p.waitForTimeout(300),clone.p.waitForTimeout(300)]);await checkpoint('sound-toggled');
// Reverse until slide 1 and stable.
lastCounter='';sameAtLast=0;for(let i=1;i<=32;i++){await click('.nav__arrow--prev');await Promise.all([orig.p.waitForTimeout(1900),clone.p.waitForTimeout(1900)]);const s=await checkpoint('reverse-'+String(i).padStart(2,'0'),i%5===0);const c=s.a.counter;if(c==='SLIDE 1/10'&&c===lastCounter)sameAtLast++;else sameAtLast=0;lastCounter=c;if(sameAtLast>=2)break}
const summary={checkpoints:results.length,allStateEqual:results.every(x=>x.equal),allCanonicalEqual:results.every(x=>x.canonicalEqual),shotChecks:results.filter(x=>x.shots).length,allShotHashesEqual:results.filter(x=>x.shots).every(x=>x.shots.equal),originalIssues:{errors:orig.errors,console:orig.consoleIssues,http:orig.httpErrors,failed:orig.failed},cloneIssues:{errors:clone.errors,console:clone.consoleIssues,http:clone.httpErrors,failed:clone.failed},timeline:results.map(x=>({label:x.label,counter:x.a.counter,active:x.a.active,equal:x.equal,shotEqual:x.shots?.equal}))};fs.writeFileSync(path.join(out,'journey.json'),JSON.stringify({summary,results},null,2));console.log(JSON.stringify(summary,null,2));await orig.ctx.close();await clone.ctx.close();await browser.close()})().catch(e=>{console.error(e);process.exit(1)})